#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
                ref class Button;
                ref class CheckBox;
                ref class TextBox;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace MoshaTypingApp
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class MainPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock1_1;
        private: ::Windows::UI::Xaml::Controls::Button^ button1_1;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkbox1_1;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkbox1_2;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkbox1_3;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkbox1_4;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkbox1_5;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkbox1_6;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock1_2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock1_3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ ractangle1_1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_6;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_7;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_8;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_9;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_10;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_11;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_12;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_13;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock2_14;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textbox2_1;
        private: ::Windows::UI::Xaml::Controls::Button^ button2_1;
        private: ::Windows::UI::Xaml::Controls::Button^ button2_2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_6;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_7;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_8;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ ractangle3_1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_9;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_10;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_11;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_12;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_13;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_14;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_15;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_16;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ ractangle3_2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_17;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_18;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_19;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_20;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_21;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_22;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_23;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_24;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ ractangle3_3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_25;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_26;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_27;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_28;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_29;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_30;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_31;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_32;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ ractangle3_4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_33;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textbox3_1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock3_34;
        private: ::Windows::UI::Xaml::Controls::Button^ button3_1;
        private: ::Windows::UI::Xaml::Controls::Button^ button3_2;
    };
}

