//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::MoshaTypingApp::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::MoshaTypingApp::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->textblock1_1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 3:
        {
            this->button1_1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button1_1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button1_1_Click);
        }
        break;
    case 4:
        {
            this->checkbox1_1 = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkbox1_1))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::checkbox1_1_Checked);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkbox1_1))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::checkbox1_1_Unchecked);
        }
        break;
    case 5:
        {
            this->checkbox1_2 = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkbox1_2))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::checkbox1_2_Checked);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkbox1_2))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::checkbox1_2_Unchecked);
        }
        break;
    case 6:
        {
            this->checkbox1_3 = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkbox1_3))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::checkbox1_3_Checked);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkbox1_3))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::checkbox1_3_Unchecked);
        }
        break;
    case 7:
        {
            this->checkbox1_4 = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkbox1_4))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::checkbox1_4_Checked);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkbox1_4))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::checkbox1_4_Unchecked);
        }
        break;
    case 8:
        {
            this->checkbox1_5 = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkbox1_5))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::checkbox1_5_Checked);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkbox1_5))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::checkbox1_5_Unchecked);
        }
        break;
    case 9:
        {
            this->checkbox1_6 = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkbox1_6))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::checkbox1_6_Checked);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkbox1_6))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::checkbox1_6_Unchecked);
        }
        break;
    case 10:
        {
            this->textblock1_2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 11:
        {
            this->textblock1_3 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 12:
        {
            this->ractangle1_1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
        }
        break;
    case 13:
        {
            this->textblock2_1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 14:
        {
            this->textblock2_2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 15:
        {
            this->textblock2_3 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 16:
        {
            this->textblock2_4 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 17:
        {
            this->textblock2_5 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 18:
        {
            this->textblock2_6 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 19:
        {
            this->textblock2_7 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 20:
        {
            this->textblock2_8 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 21:
        {
            this->textblock2_9 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 22:
        {
            this->textblock2_10 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 23:
        {
            this->textblock2_11 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 24:
        {
            this->textblock2_12 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 25:
        {
            this->textblock2_13 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 26:
        {
            this->textblock2_14 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 27:
        {
            this->textbox2_1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 28:
        {
            this->button2_1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button2_1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button2_1_Click);
        }
        break;
    case 29:
        {
            this->button2_2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button2_2))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button2_2_Click);
        }
        break;
    case 30:
        {
            this->textblock3_1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 31:
        {
            this->textblock3_2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 32:
        {
            this->textblock3_3 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 33:
        {
            this->textblock3_4 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 34:
        {
            this->textblock3_5 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 35:
        {
            this->textblock3_6 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 36:
        {
            this->textblock3_7 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 37:
        {
            this->textblock3_8 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 38:
        {
            this->ractangle3_1 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
        }
        break;
    case 39:
        {
            this->textblock3_9 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 40:
        {
            this->textblock3_10 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 41:
        {
            this->textblock3_11 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 42:
        {
            this->textblock3_12 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 43:
        {
            this->textblock3_13 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 44:
        {
            this->textblock3_14 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 45:
        {
            this->textblock3_15 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 46:
        {
            this->textblock3_16 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 47:
        {
            this->ractangle3_2 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
        }
        break;
    case 48:
        {
            this->textblock3_17 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 49:
        {
            this->textblock3_18 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 50:
        {
            this->textblock3_19 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 51:
        {
            this->textblock3_20 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 52:
        {
            this->textblock3_21 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 53:
        {
            this->textblock3_22 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 54:
        {
            this->textblock3_23 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 55:
        {
            this->textblock3_24 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 56:
        {
            this->ractangle3_3 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
        }
        break;
    case 57:
        {
            this->textblock3_25 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 58:
        {
            this->textblock3_26 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 59:
        {
            this->textblock3_27 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 60:
        {
            this->textblock3_28 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 61:
        {
            this->textblock3_29 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 62:
        {
            this->textblock3_30 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 63:
        {
            this->textblock3_31 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 64:
        {
            this->textblock3_32 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 65:
        {
            this->ractangle3_4 = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
        }
        break;
    case 66:
        {
            this->textblock3_33 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 67:
        {
            this->textbox3_1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 68:
        {
            this->textblock3_34 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 69:
        {
            this->button3_1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button3_1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button3_1_Click);
        }
        break;
    case 70:
        {
            this->button3_2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->button3_2))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MoshaTypingApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::button3_2_Click);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::MoshaTypingApp::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


